version: "3.9"
services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - BACKEND_URL=http://backend:8080
  backend:
    build: backend
    hostname: backend
    networks:
      - app-network
    volumes:
      - high_score_db:/app/db

networks:
  app-network: { }

volumes:
  high_score_db: { }